[package]
name = "gotham-server"
version = "0.1.4"
authors = [
    "gbenattar <g.benattar@gmail.com>",
    "Oded Leiba <odedleiba5@gmail.com"
]
edition = "2018"

[lib]
name = "server_lib"
path = "src/lib.rs"

[[bin]]
name = "server_exec"
path = "src/main.rs"

[dependencies]
rocket = { version = "0.4.2", default-features = false }
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json"] }
rocksdb = "0.10.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rusoto_dynamodb = "0.36.0"
rusoto_core = "0.36.0"
time-test = "0.2.1"
log = "0.4"
config = "0.9.2"
uuid = { version = "0.7", features = ["v4"] }
error-chain = "0.12.0"
failure = "0.1.5"
jsonwebtoken = "7"
rust-crypto = "0.2"
hex = "0.3.2"
floating-duration = "0.1.2"

[dependencies.curv]
package = "curv-kzen"
version = "0.7"
default-features = false

[dependencies.zk-paillier]
git = "https://github.com/KZen-networks/zk-paillier"
tag = "v0.3.12"
default-features = false

[dependencies.kms]
git = "https://github.com/KZen-networks/kms-secp256k1"
tag = "v0.3.1"
default-features = false

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"
tag = "v0.4.6"
default-features = false

[dependencies.multi-party-eddsa]
git = "https://github.com/KZen-networks/multi-party-eddsa"
tag = "v0.2.2"
default-features = false

[dependencies.multi-party-schnorr]
git = "https://github.com/KZen-networks/multi-party-schnorr"
tag = "v0.4.5"
default-features = false

[dependencies.serde_dynamodb]
git = "https://github.com/KZen-networks/serde_dynamodb"

[features]
default = ["curv/rust-gmp-kzen"]
